title: Michael D. Potter
description:
site_title: 'Michael D. Potter'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: michaeldpotter
blog_url: https://michaeldpotter.com
email: michael@michaeldpotter.com
keybase_username: 
twitter_username: 
reddit_username: 

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 

source: